### ISSUE TITLE
Introduce Brian

### ISSUE THREAD

**Issue by Brainketunze** [rago89/Incremental-development-team-6#5]
I'm a student in `HYF class11-12 group 6`
From Africa, **Cameroon**
I live in Landen in the flemish part belgium
I have one duagther call __lexie__

**Comment by tahminarasoli** [comment]
@Brainketunze  Brain Please check in project board if you have any thing more to add. :)

**Comment by snicoll** [comment]
@tahminarasoli the issue can't be ready to review since nobody can see your code. You should push your branch to GitHub and create a Pull request please.
